name: CI/CD Pipeline
on:
  pull_request:
    branches:
      - main
    types:
      - closed

jobs:
  push-to-storage:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build application
        run: npm run build

      - name: Upload build to Azure Storage
        run: |
          az storage blob upload-batch \
            --account-name <storage-account-name> \
            --account-key ${{ secrets.AZURE_STORAGE_ACCOUNT_KEY }} \
            --destination \$web \
            --source build/*
